# Analysis of Ship Noise and Ambient Sound

Erin Mee

3/7/2026

## Imports

In [2]:
from orcasound_noise.analysis.partitioned_accessor import PartitionedAccessor
from orcasound_noise.utils import Hydrophone

In [3]:
import datetime as dt
import polars as pl
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import matplotlib.pyplot as plt

## Get Ship and Sound Data

In [4]:
shipdata_path = "s3://acoustic-sandbox/ambient-sound-analysis/temp_ship_metrics/year=2026/month=02/"
ship_lf = pl.scan_parquet(shipdata_path, storage_options={'aws_region': 'us-west-2'})

In [5]:
ship_df = ship_lf.collect()

In [5]:
ship_df.head()

shape: (5, 40)
┌──────────┬─────────────┬─────────────┬──────────┬───┬────────────┬────────────┬────────────┬─────┐
│ id_track ┆ s_timestamp ┆ l_timestamp ┆ duration ┆ … ┆ comm_bb_ls ┆ comm_bb_ls ┆ min_dist   ┆ day │
│ ---      ┆ ---         ┆ ---         ┆ ---      ┆   ┆ r_q50      ┆ r_q95      ┆ ---        ┆ --- │
│ str      ┆ datetime[μs ┆ datetime[μs ┆ f64      ┆   ┆ ---        ┆ ---        ┆ f64        ┆ i64 │
│          ┆ ]           ┆ ]           ┆          ┆   ┆ f64        ┆ f64        ┆            ┆     │
╞══════════╪═════════════╪═════════════╪══════════╪═══╪════════════╪════════════╪════════════╪═════╡
│ 48972891 ┆ 2026-02-01  ┆ 2026-02-01  ┆ 88.0     ┆ … ┆ null       ┆ null       ┆ 4539.23978 ┆ 1   │
│          ┆ 23:12:24    ┆ 23:13:52    ┆          ┆   ┆            ┆            ┆ 8          ┆     │
│ 48972892 ┆ 2026-02-01  ┆ 2026-02-01  ┆ 1625.0   ┆ … ┆ null       ┆ null       ┆ 1630.26132 ┆ 1   │
│          ┆ 23:12:31    ┆ 23:39:36    ┆          ┆   ┆            ┆            ┆            ┆     │
│ 48961983 ┆ 2026-02-01  ┆ 2026-02-01  ┆ 1809.0   ┆ … ┆ null       ┆ null       ┆ 1641.05913 ┆ 1   │
│          ┆ 12:30:13    ┆ 13:00:22    ┆          ┆   ┆            ┆            ┆ 3          ┆     │
│ 48964002 ┆ 2026-02-01  ┆ 2026-02-01  ┆ 1440.0   ┆ … ┆ null       ┆ null       ┆ 2202.06740 ┆ 1   │
│          ┆ 13:53:23    ┆ 14:17:23    ┆          ┆   ┆            ┆            ┆ 6          ┆     │
│ 48952300 ┆ 2026-02-01  ┆ 2026-02-01  ┆ 1191.0   ┆ … ┆ null       ┆ null       ┆ 163.406462 ┆ 1   │
│          ┆ 03:00:16    ┆ 03:20:07    ┆          ┆   ┆            ┆            ┆            ┆     │
└──────────┴─────────────┴─────────────┴──────────┴───┴────────────┴────────────┴────────────┴─────┘

In [6]:
ship_df.describe()

shape: (9, 41)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ id_track ┆ s_timesta ┆ l_timesta ┆ … ┆ comm_bb_l ┆ comm_bb_l ┆ min_dist  ┆ day       │
│ ---       ┆ ---      ┆ mp        ┆ mp        ┆   ┆ sr_q50    ┆ sr_q95    ┆ ---       ┆ ---       │
│ str       ┆ str      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│           ┆          ┆ str       ┆ str       ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 1162     ┆ 1162      ┆ 1162      ┆ … ┆ 544.0     ┆ 544.0     ┆ 1162.0    ┆ 1162.0    │
│ null_coun ┆ 0        ┆ 0         ┆ 0         ┆ … ┆ 618.0     ┆ 618.0     ┆ 0.0       ┆ 0.0       │
│ t         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null     ┆ 2026-02-1 ┆ 2026-02-1 ┆ … ┆ -6.7774e2 ┆ -6.6362e2 ┆ 3871.0959 ┆ 12.475043 │
│           ┆          ┆ 2 23:09:1 ┆ 2 23:34:2 ┆   ┆ 3         ┆ 3         ┆ 31        ┆           │
│           ┆          ┆ 6.559380  ┆ 8.014630  ┆   ┆           ┆           ┆           ┆           │
│ std       ┆ null     ┆ null      ┆ null      ┆ … ┆ 2.1806e24 ┆ 2.1600e24 ┆ 1989.7844 ┆ 6.935769  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 11        ┆           │
│ min       ┆ 48951697 ┆ 2026-02-0 ┆ 2026-02-0 ┆ … ┆ -7.6811e2 ┆ -7.6811e2 ┆ 3.855461  ┆ 1.0       │
│           ┆          ┆ 1         ┆ 1         ┆   ┆ 4         ┆ 4         ┆           ┆           │
│           ┆          ┆ 02:01:59  ┆ 02:19:15  ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ null     ┆ 2026-02-0 ┆ 2026-02-0 ┆ … ┆ 89.390892 ┆ 96.964259 ┆ 2297.6543 ┆ 6.0       │
│           ┆          ┆ 6         ┆ 6         ┆   ┆           ┆           ┆ 49        ┆           │
│           ┆          ┆ 19:54:16  ┆ 20:15:59  ┆   ┆           ┆           ┆           ┆           │
│ 50%       ┆ null     ┆ 2026-02-1 ┆ 2026-02-1 ┆ … ┆ 98.091634 ┆ 99.672838 ┆ 3481.8431 ┆ 12.0      │
│           ┆          ┆ 2         ┆ 2         ┆   ┆           ┆           ┆ 85        ┆           │
│           ┆          ┆ 14:33:29  ┆ 14:48:00  ┆   ┆           ┆           ┆           ┆           │
│ 75%       ┆ null     ┆ 2026-02-1 ┆ 2026-02-1 ┆ … ┆ 99.626515 ┆ 99.89737  ┆ 5467.3328 ┆ 18.0      │
│           ┆          ┆ 8         ┆ 8         ┆   ┆           ┆           ┆ 35        ┆           │
│           ┆          ┆ 09:50:47  ┆ 09:57:18  ┆   ┆           ┆           ┆           ┆           │
│ max       ┆ 49373155 ┆ 2026-02-2 ┆ 2026-02-2 ┆ … ┆ 99.994273 ┆ 99.996302 ┆ 17423.061 ┆ 26.0      │
│           ┆          ┆ 6         ┆ 6         ┆   ┆           ┆           ┆ 877       ┆           │
│           ┆          ┆ 00:51:43  ┆ 01:15:50  ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [41]:
bb_path = "s3://acoustic-sandbox/ambient-sound-analysis/data_2.0/broadband/hydrophone=orcasound_lab/year=2026/month=02/"
#bb_schema = pl.Schema({"__index_level_0__": dt.datetime,"0": pl.Float64})
bb_df = pl.scan_parquet(bb_path, storage_options={'aws_region': 'us-west-2'}).sort("__index_level_0__")

## Analysis

### Frequency of Ship Passings and Broadband

In [87]:
bb = (
    bb_df
    .group_by_dynamic("__index_level_0__", every="3h")
    .agg(pl.col("0").mean().alias("bb_avg"))
    .filter(pl.col("bb_avg") > -20)
    .sort("__index_level_0__")).collect()

In [73]:
ship_subset = ship_df.filter(pl.col("type").is_in(["cargo", "tanker"]))

In [93]:
fig = make_subplots(
    rows=2,
    cols=1,
    shared_xaxes=True,
    row_heights=[0.3, 0.7],
    vertical_spacing=0.05
)
fig.add_trace(
go.Scatter(
    x=bb["__index_level_0__"],
    y=bb["bb_avg"],
    mode="lines",
    name="Broadband Sound Level"
), row=1, col=1)

# Duration in milliseconds
duration_ms = (ship_subset["l_timestamp"] - ship_subset["s_timestamp"]).dt.total_seconds() * 1000

fig.add_trace(
    go.Bar(
        x=duration_ms,
        y=ship_subset["type"],
        base=ship_subset["s_timestamp"],
        orientation="h",
        name="Ship Passages"
    ), row=2, col=1)

fig.update_layout(
    barmode="overlay",
    height=600,
    template="simple_white"
)

fig.update_xaxes(type="date")
fig.update_xaxes(showline=False, showticklabels=False, tickcolor="white", row=1, col=1)
fig.show()

### Ship Passage Timeline

In [ ]:
fig = px.timeline(ship_df, 
                    x_start="s_timestamp", 
                    x_end="l_timestamp", 
                    y="type", color="type", 
                    hover_data="bb_q95", 
                    template="simple_white", 
                    title="Ship Presence Timeline")
fig.show()

### Tanker Ship Crossing PSD

In [121]:
bb = (
    pa.bb_df
    .group_by_dynamic("__index_level_0__", every="1m")
    .agg(pl.col("0").mean().alias("bb_avg"))
    .sort("__index_level_0__")).collect()

In [128]:
start_time = dt.datetime(2026, 2, 11, 16, 43)
end_time = dt.datetime(2026, 2, 11, 17, 51)
psd_ship = pa2.psd_df.filter(pl.col("__index_level_0__").is_between(start_time, end_time)).collect()
bb_ship = pa2.bb_df.filter(pl.col("__index_level_0__").is_between(start_time, end_time)).collect()
ship_z = psd_ship.select(pl.exclude("__index_level_0__")).to_numpy().transpose()

In [129]:
fig = make_subplots(rows=2, cols=1, row_heights=[0.3,0.7], shared_xaxes=True, vertical_spacing=0.02)

fig.add_trace(go.Scatter(x=bb_ship["__index_level_0__"], y=bb_ship["0"], line=dict(color="#32006e", width=2)), row=1, col=1)

fig.add_trace(go.Heatmap(x=psd_ship["__index_level_0__"], y=psd_ship.columns, z=ship_z, zmin=0, zmax=30, colorscale='Viridis',
                    colorbar={"title": 'Magnitude'}), row=2, col=1)
    
fig.update_layout(
    legend_title="Magnitude",
    margin=dict(l=50, r=50, t=50, b=50),
    template="simple_white"
    )
fig.update_yaxes(title_text="Frequency (Hz)", type="log", row=2, col=1)
fig.update_yaxes(title_text="Decibels re 1 a.u.", row=1, col=1)
fig.update_xaxes(showline=False, showgrid=False, row=1, col=1)

### Cargo Ship Crossing

In [34]:
start_time = dt.datetime(2026, 2, 24, 19, 45)
end_time = dt.datetime(2026, 2, 24, 20, 50)
psd_ship = pa4.psd_df.filter(pl.col("__index_level_0__").is_between(start_time, end_time)).collect()
ship_z = psd_ship.select(pl.exclude("__index_level_0__")).to_numpy().transpose()

In [37]:
fig = go.Figure(
    data=go.Heatmap(x=psd_ship["__index_level_0__"], y=psd_ship.columns, z=ship_z, zmin=0, zmax=30, colorscale='Viridis',
                    colorbar={"title": 'Magnitude'}))
fig.update_layout(
    xaxis_title="Time",
    yaxis_title="Frequency (Hz)",
    legend_title="Magnitude",
    margin=dict(l=50, r=50, t=50, b=50)
    )
fig.update_yaxes(type="log")

### Cargo ships Speed vs Sound Level

In [ ]:
# cargo_df = (
#             ship_df
#             .filter(pl.col("type") == "cargo")
#             .filter(pl.col("bb_avg") > 0))
cargo_df = ship_df.filter(pl.col("bb_avg") > 0)
fig = go.Figure(
    data=go.Scatter(x=cargo_df["max_speed"], y=cargo_df["bb_q95"]*cargo_df["distance"], mode="markers", hovertext=cargo_df["name"])
)
fig.update_layout(
    xaxis_title="Speed (knots)",
    yaxis_title="Sound Level (Relative Decibels)",
    )

### Duration and Sound Level of Ships

In [137]:
fig = px.scatter(ship_df.filter(pl.col("bb_q95") > 0), x="duration", y="bb_q95", color="type")
fig.update_layout(
    xaxis_title="duration (s)",
    yaxis_title="Sound Level (Relative Decibels)",
    )
fig.show()